layout_spectrum: 0.1212766
typography_spectrum: 0.5595745
color:
  saturation: 0.8765957
  lightness: 0.687234
  brandStrength: 0
  rhythmicContrast: 0.8489361
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
name: Valorfitnessinternational.com
